### ISSUE TITLE
載入的Library未使用https

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#1018]
目前抓到的：

- http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js
- http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700

**Comment by dd-han** [comment]
網誌圖片網址也沒https：

- http://labfnp.com/assets/labfnp/img/update1.jpg

有一種解法式設定CDN跟圖片素材的時候，用 `//labfnp.com/assets/labfnp/img/update1.jpg` 取代 `http://labfnp.com/assets/labfnp/img/update1.jpg` 或 `https://labfnp.com/assets/labfnp/img/update1.jpg`

瀏覽器看到 `//` 開頭就會自動偵測原本的網頁是http或https載入元件

**Comment by smlsunxie** [comment]
用 `//labfnp.com/assets/labfnp/img/update1.jpg` 取代即可

**Comment by smlsunxie** [comment]
`<script type="text/javascript" src="http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js"></script>`

這個直接複製一份到本地 `assets`

`<script type="text/javascript" src="/js/jquery.unveil.js"></script>`

這個移到 `assets` 底下

**Comment by dd-han** [comment]
@smlsunxie 後來我發現Microsoft的CDN也有提供https

還要複製嗎？

**Comment by smlsunxie** [comment]
還是複製一份，library 版本才能控制，也方便之後進行載入優化
