### ISSUE TITLE
font還沒全部從 https 載入

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#1025]
![image](https://cloud.githubusercontent.com/assets/5909203/20048024/62ec395a-a4f4-11e6-8c9d-6825f1a9563a.png)

- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.ttf
- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.woff
- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.ttf
- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.woff
- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.ttf
- http://beta.labfnp.com/assets/labfnp/fonts/BellMT.woff

**Comment by smlsunxie** [comment]
路徑統一改成 `//assets` 開頭

**Comment by dd-han** [comment]
如果要留domain應該是 `/assets` 開頭

或是 `//beta.labfnp.com/assets/labfnp/fonts/BellMT.woff`
