### ISSUE TITLE
api/labfnp/recipe洩漏了私密配方

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#1049]
用curl無Cookie的狀態下，可以把私密配方的配方叫出來

**Comment by dd-han** [comment]
`api/labfnp/recipe/[number]` 有阻擋路人看配方

可是 `api/labfnp/recipe` 後面帶查詢參數（從後台可以複製）是可以把配方吐出來的。

另外 `api/labfnp/recipe` 的 `PUT` 指令沒有檔人，所以普通User可以去更新管理員創作的香水。

**Comment by FuYaoDe** [comment]
api/labfnp/recipe 已修正
api/labfnp/recipe 尚未修正，需要把 action 移動到 admin 的 controller
