### ISSUE TITLE
動態不要顯示 type=status

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#1061]
1. 已經存在的資料，將資料庫中已經存在的動態，只要 type=status 就設定 publish=false
2. 再從 FB API 匯入資料時，只要 type=status 就預設  publish=false

![image](https://cloud.githubusercontent.com/assets/698579/20244982/422db5f0-a9d0-11e6-999b-a3dc7e8e00b2.png)

**Comment by smlsunxie** [comment]
在 migrate sql 撰寫舊資料更新語法
