### ISSUE TITLE
未登入除了加上 class 彈登入視窗外 <a> 裡面的 href 不要加上網址，爬蟲會爬到 

### ISSUE THREAD

**Issue by FuYaoDe** [trunk-studio/cargocms#1085]
目前有發現
`/recipe/order/XXXX`
`/recipe/feedback/XXXXX`

![screenshot 2016-11-18 14 20 15](https://cloud.githubusercontent.com/assets/6357215/20420689/57de34ec-ad9a-11e6-83b5-a8fb75f9d94f.png)

**Comment by lyhcode** [comment]
可以用 `href="#"`  因為 `<a>` 一定要有 href 才 valid

然後為了讓 needLogin 作用，可以另外設計 `data-url` 來放實際要存取的網址

**Comment by lyhcode** [comment]
另外 `needLogin` 命名可以再調整地更有系統化規則，例如：

```
fn-signin-required
```
