### ISSUE TITLE
記憶體使用量測試

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#1117]
確認 production mode 是否已經將 memory session 關閉

記憶體壓力測試結果，可以使用下面網頁的做法

https://segmentfault.com/a/1190000004888348

壓力測試可以設置要測試的網頁，並且在壓力測試時使用 production mode，將結果產出 excel 或是 csv

再透過 api 讀出測試前跟測試後的記憶體用量，以便透過該 api 判斷記憶體使用是否有異常

**Comment by smlsunxie** [comment]
目前測試記憶體使用量，在運行壓力測試前跟後

```
=== before traffic test memoryUsage ===
{ rss: 367628288, heapTotal: 333033248, heapUsed: 306478880 }
=== after traffic test memoryUsage ===
{ rss: 826519552, heapTotal: 781850144, heapUsed: 453890416 }
child process exited with code 0
```

上面每一個值的解釋可以參考： http://stackoverflow.com/a/38049633

先看 `heapUsed` 目前看來是有明顯增加的，根據這個結果進行相關改善指標

**Comment by dd-han** [comment]
目前的測試參數是這樣：

- 連續跑60秒
- 10個使用者
- 每個使用者開20個GET請求


還沒做完的功能如下：

- 建立壓力測試專用設定檔（ Production mode 、 Sails的記憶體量輸出Excel ）
- 進行有流程的壓力測試
- 更容易調整測試參數
- 更容易設定每個流程允許的Timeout
