### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#1147]
後台來回重複切換各項功能會出現

![image](https://cloud.githubusercontent.com/assets/698579/20745731/8c30214c-b71d-11e6-8265-71d5fa285d28.png)

**Comment by tikka0910** [comment]
重現方式：在載入頁面時，如果「資料還沒載入完成」就切換至另一個介面後，就會跳出警告訊息。

**Comment by FuYaoDe** [comment]
點選功能時，畫面載入中新增 mask
沒有載入完成不能點選其他功能，避免載入不完整
mask 要包到 menu sidebar
