### ISSUE TITLE
票卷資訊缺少足夠的提示讓USER知道點下去可以展開詳細資訊

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#1150]
![image](https://cloud.githubusercontent.com/assets/698579/20761096/decad048-b75c-11e6-83ce-de13dc74d164.png)

![image](https://cloud.githubusercontent.com/assets/698579/20761121/e9d10c00-b75c-11e6-8866-10031091390e.png)

**Comment by FuYaoDe** [comment]
`我的訂單`  部分也有使用相同 list 好要一併修正
