### ISSUE TITLE
safari 導航列跑版

### ISSUE THREAD

**Issue by sakuxz** [trunk-studio/cargocms#1343]

**Comment by tikka0910** [comment]
<img width="288" alt="2017-02-14 11 53 01" src="https://cloud.githubusercontent.com/assets/8611890/22914592/4be0b6f4-f2ac-11e6-9ae5-73e13eb6d3e9.png">
![2017-02-14 11 52 35](https://cloud.githubusercontent.com/assets/8611890/22914593/4be1cf58-f2ac-11e6-9039-4bd65274bde1.png)

**Comment by tikka0910** [comment]
![2017-02-14 11 52 35](https://cloud.githubusercontent.com/assets/8611890/22914632/8947f46c-f2ac-11e6-8c41-ac57e2db0bd9.png)
