### ISSUE TITLE
b2b react-ship 列印出貨單 功能

### ISSUE THREAD

**Issue by tikka0910** [trunk-studio/cargocms#1366]
按下「列印出貨單」產生新的靜態頁面，內容為完整的出貨單內容，方便使用者列印

http://blog.xuite.net/tolarku/blog/447081329-%5BHTML%2BJS%5D+%E5%88%97%E5%8D%B0%E6%8C%87%E5%AE%9A%E5%8D%80%E5%A1%8A%E7%B6%B2%E9%A0%81%E5%85%A7%E5%AE%B9

**Comment by alincode** [comment]
直接用 CSS 語法，應該會更單純。
<style type="text/css" media="print"> </style>
