### ISSUE TITLE
結帳功能應該有進度提示

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1408]
![image](https://cloud.githubusercontent.com/assets/1522808/21916282/80352958-d97a-11e6-919b-ac2be7642a72.png)

## 參考
建議使用 `Bootstrap Form Process Steps`

http://www.designerslib.com/bootstrap-form-process-steps/

**Comment by VagrantPi** [comment]
![image](https://cloud.githubusercontent.com/assets/12500724/26577303/892c9924-455e-11e7-97be-814a06a6a49a.png)

![image](https://cloud.githubusercontent.com/assets/12500724/26577248/5b8cf1e4-455e-11e7-9177-e1c509fc30f8.png)

這樣 OK 嗎?

**Comment by alincode** [comment]
如果只有兩步驟的話，進度條感覺太長，應該可以縮寫一點，也許可以加個步驟階段？

![](http://www.designerslib.com/wp-content/uploads/2015/09/bootstrap-form-process-step.jpg)

**Comment by VagrantPi** [comment]
![image](https://cloud.githubusercontent.com/assets/12500724/26589650/1b8979e6-458b-11e7-8a63-17bdfa5d626d.png)
![image](https://cloud.githubusercontent.com/assets/12500724/26589684/2d8fddce-458b-11e7-8932-f98cef96ca45.png)

這樣呢??

**Comment by kuyen** [comment]
ＱＱ @VagrantPi  我發現我上面有寫，建議你用這個比較好 

https://bootsnipp.com/snippets/featured/form-process-steps
（也就是 @ALiangLiang 貼的那個）

原因是這個有數字提示以及進度描述
