### ISSUE TITLE
需要預防重複訂購的情況，會出現多筆一樣的訂單

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1429]

**Comment by FuYaoDe** [comment]
重複訂單要用 token 去擋
token model 設定 unique
controller 在 render view 時要給個 input value=token 每次重新整理都不一樣
然後送出的時候也把 token 送出存進資料庫
如果 token 有重複 create 時會被 sql 擋掉
這樣子就能保證訂單完全沒有重複的情況
lfp 是這樣處理的
