### ISSUE TITLE
mobi 前台沒有顯眼的下單按鈕

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1574]
前台的購物車按鈕藏得太深了
![image](https://cloud.githubusercontent.com/assets/1522808/23018411/d0745af6-f478-11e6-9c4a-11a233bb9abc.png)
-----------------------------------
購物車展開
![image](https://cloud.githubusercontent.com/assets/1522808/23018432/e2f225dc-f478-11e6-9060-6b2f54d9c279.png)
-----------------------------------
應該可以做成類似如下
![image](https://cloud.githubusercontent.com/assets/1522808/23018390/c1158c1a-f478-11e6-8651-2d966da9a649.png)
-----------------------------------
犀牛盾 shopify
![image](https://cloud.githubusercontent.com/assets/1522808/23018548/50fe855c-f479-11e6-8238-4038fa6131e4.png)

**Comment by VagrantPi** [comment]
![image](https://cloud.githubusercontent.com/assets/12500724/26799186/25a8fa6a-4a67-11e7-8a3e-0d9c204c4fec.png)

這樣 OK 嗎??
