### ISSUE TITLE
部分前端 review

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#1583]
https://github.com/trunk-studio/cargocms/blame/improvedLogin/react-app-ship/src/views/ShippedListView/components/ShipCardDetail.js

**Comment by sakuxz** [comment]
https://github.com/trunk-studio/cargocms/blame/improvedLogin/react-app-ship/src/views/ShippedListView/components/ShipCardDetail.js#L80
https://github.com/trunk-studio/cargocms/blame/improvedLogin/react-app-ship/src/views/ShippedListView/components/ShipCardDetail.js#L98
改用 margin

https://github.com/trunk-studio/cargocms/blame/improvedLogin/react-app-ship/src/views/ShippedListView/components/ShipCardDetail.js#L79
應該不須要用 .row > .col-xs-12 吧
div 本身不就一整列了嗎

**Comment by tikka0910** [comment]
![2017-02-18 1 16 13](https://cloud.githubusercontent.com/assets/8611890/23090611/8328157a-f5dc-11e6-908a-5fa09bdaa198.png)
