### ISSUE TITLE
b2b 前台 product list 要加入超大螢幕支援

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1585]
目前只有 col-sm-4 col-md-3

col-sm-4 col-md-3@1440px
![image](https://cloud.githubusercontent.com/assets/1522808/23091717/602e5b68-f5f7-11e6-8301-3c9738a29487.png)

---------------------
col-sm-4 col-md-3@2560px

![image](https://cloud.githubusercontent.com/assets/1522808/23091558/bfc793f4-f5f3-11e6-85c5-a9d34fc9ada0.png)

---------------------

lg-2  @1440px

![image](https://cloud.githubusercontent.com/assets/1522808/23091583/7632af8e-f5f4-11e6-8594-780b5f0f0928.png)

---------------------

lg-2  @2560px

![image](https://cloud.githubusercontent.com/assets/1522808/23091587/88952de6-f5f4-11e6-8ace-d620ec37eb9d.png)

================

lg-2 看來效果在 1440 左右時並不好，但bootstrap v3 只支援到 >=1200 

可以考量升級到 v4 多加一個等級，或是限制商品區版面 RWD 最大寬度
![image](https://cloud.githubusercontent.com/assets/1522808/23091605/bf66188a-f5f4-11e6-98d8-5163d55914c7.png)

**Comment by tikka0910** [comment]
內部討論結果，將畫面最大寬度 fix 在 1920px
