### ISSUE TITLE
參考資料

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1638]
# 全部

- https://github.com/trunk-studio/cargocms/issues/1624

# 本期目標

# 1. 前台商品細目頁面

## 資料範例
- https://github.com/trunk-studio/cargocms/issues/1630
- https://github.com/trunk-studio/cargocms/issues/1631
- https://github.com/trunk-studio/cargocms/issues/1632
- https://github.com/trunk-studio/cargocms/issues/1633

## 欄位列表
- 品名：(20字元)
- 產地：
- 規格：
- 產品介紹：
- 產品規格： 
- 注意事項：

## 樣式
- 產品規格
![](https://cloud.githubusercontent.com/assets/25861877/23828669/5d23b34a-0714-11e7-9c2f-68c3e911d89b.png)
- 標題與細目
![](https://i.imgur.com/WW9bLc6.png)

# 2. 前台-產品 QA

## 資料範例
- https://github.com/trunk-studio/cargocms/issues/1629

## 欄位列表
- 購物常見問題
    - 1. 如何線上訂購?
    - 2. 我已下訂單了，如何取消訂單或更改訂購內容?
    - 3. 目前雲端漁場提供哪些付款方式?
    - ...
- 出貨常見問題
    - ...
- 退貨換貨常見問題
- 發票常見問題

## 樣式
參考 Lative:
- https://www.lativ.com.tw/Page/return_product_and_withdraw_questions

![](https://i.imgur.com/5todNTM.png)

# 3. 付款方式

## ATM
- 後台需要可以修改固定之 ATM 匯款帳號
- 消費者付款後確認流程如下：（人工對帳）
    - 消費者付款完成 > 打電話通知 > 後台人員對帳 > 後台人員更改訂單

## 貨到付款
- 如消費者選擇貨到付款，則後台須提供貨運單號欄位

# 4. 營業稅

ref:
#1691 
#1692

**Comment by kuyen** [comment]
商品稅率處顯示試算

**Comment by dd-han** [comment]
OpenCart 的設計是這樣：

1. 有一個頁面設計各種 Option 清單
2. 商品頁面可以選擇套用哪些 Option 清單（可以套用一份清單、也可以套用多份清單）
3. 結帳頁面就會顯示 Option

抉擇點：
要不要讓 Option 獨立出來。

Option 獨立出來的好處與壞處：
寫好一組 Option 可以套用到多個商品上，但是如果幾乎每個商品都有自己的一組 Option ，反而會變成很難找。

Option 綁定商品的好處：
Option 就直接屬於商品，不會有對應或是清單很長很難找的問題。但是如果兩個商品套用同樣的 Option ，變成要手動複製貼上。

參考圖片：
![2017-04-07 16_04_15-options - yandex browser](https://cloud.githubusercontent.com/assets/5909203/24791386/749c0228-1bac-11e7-99cc-3466917ef7d7.png)
![2017-04-07 16_04_19-products - yandex browser](https://cloud.githubusercontent.com/assets/5909203/24791387/74a2ac5e-1bac-11e7-8213-5ebc93fa89af.png)
![2017-04-07 16_04_23-samsung galaxy tab 10 1 - yandex browser](https://cloud.githubusercontent.com/assets/5909203/24791388/74a3934e-1bac-11e7-9a4e-9ec2dffbebbb.png)

**Comment by tikka0910** [comment]
https://www.sushigogo.com.tw/sushigogo/

參考產品頁面
