### ISSUE TITLE
前台購物車 navbar 設為 fixed

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#1726]
## <strong>其他</strong>
1.建議購物說明/登入/購物車鎖在上方

![image](https://cloud.githubusercontent.com/assets/25861877/25688819/d30a11b6-30b4-11e7-96be-2673d83a2ac1.png)

**Comment by ALiangLiang** [comment]
目前fixed後
其他版面會往上佔據原本navbar位置的狀況
