### ISSUE TITLE
Blog 文章分享按鈕

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#205]
![image](https://cloud.githubusercontent.com/assets/698579/17721437/b934ee3e-645c-11e6-9656-ff4f22fb2b38.png)

**Comment by smlsunxie** [comment]
google plus 應該已經沒什麼人用了，我覺得 facebook 跟 twitter 即可

**Comment by lyhcode** [comment]
不建議依我們自己的需求，這個可以讓客戶自己決定要或不要，做的時候多做一顆 Google+ 按鈕，頂多是增加幾分鐘；但如果後面才要補加，討論的時間就不止。

所以可以寫成一個套件，方便切換。

其他功能的原則也是這樣，能順手做掉的，就不要在當下省幾分鐘。

**Comment by smlsunxie** [comment]
了解

**Comment by lyhcode** [comment]
spec:

```
<!-- 不要直接用按鈕呈現，要讓內容有意義-->
<a href="http://cargo-dev.trunksys.com/post/xxx永久連結" class="social-share-button">Share</a>
```

透過 jQuery Plugin 把上面的連結變成按鈕。

```
$(function() {
  $('.social-share-button').createCargoSocialButton();
});

```

**Comment by FuYaoDe** [comment]
可跟 #157  一起做

**Comment by FuYaoDe** [comment]
https://github.com/kni-labs/rrssb
