### ISSUE TITLE
主要流程：建立配方後，可以填寫回饋資料

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#262]
PS. 要輸入一組由門市人員建立的代碼，代碼正確才會把該資料列入積分

代碼不正確，一樣可以送出，但是感覺描述的加權給 0 分，不列入計算

如果代碼先被 user 輸入，門市人員補登代碼時，要找到已經輸入過的 recipe 進行補加權動作

![image](https://cloud.githubusercontent.com/assets/698579/17886873/69f77b30-6956-11e6-903e-feebb721c406.png)

**Comment by smlsunxie** [comment]
1. 進行下訂，不管線上或是線下要可以進行回饋
2. 為了要能夠收集已經購買的項目的回饋，個人頁面需要有已訂購清單
3. 從訂購清單可以點選要回饋的已購買的香水，檢視香水內容後進行回饋
4. 若有回饋過在訂購清單上需要顯示已回饋的狀態
5. 線上購買在收到成品時應該也會有發票可以進行回饋？

**Comment by lyhcode** [comment]
已訂購記錄應該可以附屬在 配方明細的畫面

```
// 配方內容，頁面下方，FB留言回應的上方

if (訂單.作者 == 登入帳號) {
  for each 訂購明細 {
    show 訂購時間等摘要
  }
}
```

**Comment by lyhcode** [comment]
回饋不要 by 訂購，應該要 by 配方

一個配方，允許 一個 user 對 一個配方 填寫回饋，如果訂購多次，每次訂購後都寫回饋，就會覆蓋掉舊的。

至於舊的回饋資料要不要保存歷史記錄，我是覺得如果有會比較好

**Comment by lyhcode** [comment]
第5點

如果是線上訂購，在線上出貨的流程中，應該是由理貨人員幫訂單填上發票編號，這時候就可以自動帶發票資料進去了

**Comment by lyhcode** [comment]
為什麼不要 by 訂購單做回饋（每次訂購都可以有一筆對應的回饋），是因為這樣會把流程和介面變得複雜，對USER來說是很難操作的，必須考慮 UX

**Comment by smlsunxie** [comment]
關於 https://github.com/trunk-studio/cargocms/issues/262#issuecomment-247915211

你要表達的意思是不是 

```
if (訂單.訂購者 == 登入帳號) {
  for each 訂購明細 {
    show 訂購時間等摘要
  }
}
```

如此每個人對於單一配方若有多次購買的話也可以滿足

關於回饋資料的收集，其中感覺的收集，提供類似從感覺建立可篩選清單，讓使用者進行操做

回饋部分，新增 model 記錄，  `RecipeFeelingFeedbak`
```
OrderId
RecipeId
InvoiceNo
feeling
createAt
```

**Comment by lyhcode** [comment]
上面改了，應該是

```
if (配方.作者 == 登入帳號) {
```

**Comment by smlsunxie** [comment]
但有可能會買別人的配方，除了自己做的之外，還是說不用考慮買其他人的配方的情形？

若是只會買自己的

`if (配方.作者 == 登入帳號) {`

有可能買別人的配方的話

`if (訂單.訂購者 == 登入帳號 && 訂單.配方 == 檢視的配方) {`

**Comment by smlsunxie** [comment]
model 部分

RecipeFeedback
```
UserId
RecipeId
invoiceNo
invoiceNoCheck
feeling //多筆感覺用 `,` 隔開
createAt
```

其中移除 Order 是因為需求上，有可能不需要下訂，也可以對配方進行回饋，因此不需要對訂單做關聯

新增 invoiceNoCheck 則是門市人員，會根據有輸入的發票號碼的配方，進行比對，若確實有購買紀錄則進行打勾，以便後續修正配方的感覺

現階段，透過前台對配方限制最多輸入 5 個感覺，每個人都可以對配方進行感覺回饋， 若有重覆回饋的，需要將之前曾經輸入過的資料在帶出進行修改。

**Comment by smlsunxie** [comment]
新增 UserId 每個人對單一配方最多一筆 RecipeFeedback
