### ISSUE TITLE
新增配方頁面 - 從感覺回選配方功能

### ISSUE THREAD

**Issue by kuyen** [trunk-studio/cargocms#347]
![image](https://cloud.githubusercontent.com/assets/1522808/18344971/0464d84c-75ec-11e6-94a6-2afd9ae52a00.png)

![image](https://cloud.githubusercontent.com/assets/1522808/18344868/a00d0932-75eb-11e6-9dd5-49d35b9d254a.png)

**Comment by smlsunxie** [comment]
柏均回應：

方案一好像比較簡單而且直覺， 但方案一這邊可能有幾點想要加上或是留意的

1. 香味感覺的選項分布是否可以調整成Random分布（避免氣味選擇上大家都只選到前面的選項）
2. 若是在第一個香味分子選擇了"TA66"某一個香料時，若他選擇到某一個感覺同時這個感覺內，也有"TA66"這個選項，若他還是點選TA66的話，可能要有個氣泡通知，此香料已經選用。
3. 第三點我覺得蠻重要的是當使用者選擇了感覺，並從對應感覺看到了多個香味分子時，如："BA61"與"MA65"這兩個香味分子，當他選到其中的"BA61"時，可否於局部區塊顯示他所有或部分（ex:scored>2以上）的氣味感覺描述標籤

採用第一個方案並且最後加上一個步驟，把選取到的香味分子的感覺呈現出來

**Comment by smlsunxie** [comment]
total repeat: 資料庫出現的次數
score：人在回報感覺時，對某香味給予特定感覺的次數

**Comment by smlsunxie** [comment]
點選 創作一個配方

![image](https://cloud.githubusercontent.com/assets/1689227/18408784/40312020-776c-11e6-9101-04fc2a6d6d3c.png)

出現類似

![image](https://cloud.githubusercontent.com/assets/1689227/18408793/6ecfb91e-776c-11e6-92d2-b07824e7937d.png)

兩個選項

1. 從感覺出發
2. 從香味出發

從香味出發，用原本的做法
從感覺出發，則使用此 issue 的流程

**Comment by smlsunxie** [comment]
form 表單在 

views-labfnp/labfnp/recipe/edit.ejs
views-labfnp/labfnp/recipe/create.ejs

共用

https://github.com/trunk-studio/cargocms/blame/feature/%23347/views-labfnp/labfnp/recipe/edit.ejs#L25

現在在

views-labfnp/labfnp/recipe/form.ejs

需要多一層判斷是要載入從感覺還是從香味開始的建立表單

**Comment by smlsunxie** [comment]
切換創作方式使用

* url?from=feeling
* url?from=scent

**Comment by smlsunxie** [comment]
使用 displayFeeling 進行 scent 清單的篩選

https://github.com/trunk-studio/cargocms/blame/feature/%23347/api/models/labfnp/Scent.js#L41

**Comment by smlsunxie** [comment]
第三步驟之 tag 顯示參考

上面顯示敘述，下面顯示  tag

![image](https://cloud.githubusercontent.com/assets/1689227/18409535/01b9b0ae-777c-11e6-8fdd-de97cf50a3e4.png)

![image](https://cloud.githubusercontent.com/assets/1689227/18409532/ee5e4eca-777b-11e6-9bc5-0ec3d6108269.png)

**Comment by smlsunxie** [comment]
使用 server side pagging 進行塞選及排序

http://localhost:5001/api/labfnp/feeling?serverSidePaging=true&draw=0&columns[0][data]=scentName&columns[0][searchable]=true&columns[0][search][regex]=false&columns[1][data]=score&columns[1][searchable]=false&columns[1][search][regex]=false&order[0][column]=1&order[0][dir]=desc&start=0&length=10&search[value]=BU2

**Comment by smlsunxie** [comment]
參考 #355 

前端表單送出時，新增 createdBy input，後端將會記錄該欄位
