### ISSUE TITLE
firefox與Edge在由感覺創作頁面中，選擇分子功能異常

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#461]
由香味分子創作則沒問題

![firefox](https://cloud.githubusercontent.com/assets/5909203/18519254/d5fbe5ba-7ad5-11e6-8823-2eb67e2f4b2c.png)

**Comment by dd-han** [comment]
不只Firefox異常，Edge也異常

![edge](https://cloud.githubusercontent.com/assets/5909203/18519354/3de69396-7ad6-11e6-919d-19511812371f.png)

**Comment by dd-han** [comment]
IE11正常

**Comment by sakuxz** [comment]
@dd-han  
我的 firefox 48 選丁香沒這個問題阿
你是用哪一版

**Comment by dd-han** [comment]
Firefox 48 on ArchLinux，我再測試一次新版看看還有沒有這個問題

**Comment by dd-han** [comment]
看起來Firefox隨著其他bug修好了，Edge稍後確認是不是也ok了

**Comment by kuyen** [comment]
兩位這應該是因為該感覺本來就沒有氣味分子了，我正在檢查中

**Comment by dd-han** [comment]
我確定那時候點了五六個感覺，出來的香味分子都沒東西，難道我運氣真的太好怎麼點都沒東西嘛（驚）
