### ISSUE TITLE
會員服務條款內容沒有做完

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#470]
![image](https://cloud.githubusercontent.com/assets/698579/18521754/fa34ca50-7adf-11e6-8113-8eafaedf7dea.png)

**Comment by dd-han** [comment]
我這邊看有正常的捲軸可以捲到底

![2016-09-15 01-02-58](https://cloud.githubusercontent.com/assets/5909203/18521819/30b230cc-7ae0-11e6-99f5-224058451f24.png)
