### ISSUE TITLE
手機版文字雲跟圓餅圖問題不少

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#473]
打橫沒有沾滿版面、文字超擠
![screenshot_20160915-012656](https://cloud.githubusercontent.com/assets/5909203/18522708/bde53274-7a76-11e6-9b72-3c25642b9c29.png)
![screenshot_20160915-012709](https://cloud.githubusercontent.com/assets/5909203/18522717/c684f068-7a76-11e6-9a46-4a828afc2ec8.png)

**Comment by smlsunxie** [comment]
文字雲可以修正若為手機版，限制文字雲出現文字個數

參考這段： https://github.com/trunk-studio/cargocms/blame/develop/assets-labfnp/page/wordCloud.js#L94-L106

目前是參考長寬，可以根據顯示區塊給予合適的詞數
手機的話，就以最多顯示 10 個字為限

圓餅圖的話也是做類似處理

**Comment by dd-han** [comment]
延伸問題： #544
