### ISSUE TITLE
香味分子的欄位太多，描述欄位文字太長，這個UI呈現不合理

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#489]
![image](https://cloud.githubusercontent.com/assets/698579/18537624/85c5615c-7b39-11e6-9341-b5bb21248c7f.png)

**Comment by kuyen** [comment]
![image](https://cloud.githubusercontent.com/assets/1522808/18540574/2cc68450-7b52-11e6-9071-69cf8bff9fc5.png)
