### ISSUE TITLE
活動發佈與報名頁面

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#527]
參考畫面

![image](https://cloud.githubusercontent.com/assets/1689227/18624782/c2575508-7e7c-11e6-8f96-4482567dfee8.png)

功能需求
## 活動事件建立

以 post model 為基礎

event 的說明頁面直接使用 post 的 model

post 可關聯 event model

其中為了建立活動頁面新增 event model

post 一對多 event

欄位為

```
limit
price
title
saleStartDate
saleEndDate
eventStartDate
eventEndDate
```

為了紀錄報名資料新增 eventRegister model

```
EventId
UserId
```

需要與 Allpay 關聯

前台新增活動的頁籤
## 取消報名

待討論

**Comment by FuYaoDe** [comment]
Event Model 新增 alias 欄位來放 url 別名
`/events/:name`
