### ISSUE TITLE
需要想一個地方或一個新畫面讓使用者能輸入香味分子的感覺

### ISSUE THREAD

**Issue by FuYaoDe** [trunk-studio/cargocms#545]

**Comment by smlsunxie** [comment]
香味分子感覺回饋

`scent/feedback` 

檢視配方時，新增香味分子回饋

![image](https://cloud.githubusercontent.com/assets/1689227/19028977/901a85da-8974-11e6-979f-8cec38296289.png)

針對此配方所選的香味分子進行感覺回饋

![image](https://cloud.githubusercontent.com/assets/1689227/19029010/d85f850c-8974-11e6-8a00-29ff6cb75060.png)

**Comment by smlsunxie** [comment]
與 @kuyen 討論，以他實際操作的經驗，在建立配方時一併收集會是比較好的呈現方式，可以在跟客戶確認做法
