### ISSUE TITLE
活動報名系統 MEMO

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#546]
Type 活動類型
1. BUILTIN 內建活動
2. EXTERNAL 外連活動（Accupass or KKTIX）

在活動頁面 `/events` 顯示所有活動（包括：內建 & 外連），用日期排序，最新活動顯示在最上面

如果是內建活動，則使用內建報名 & 繳費系統

如果是外連活動，則直接連結外部

**Comment by dd-han** [comment]
動報名系統要增加第三種設計：直接轉址到 accupass

例如 /events/ESLITE20161019/ 就會自動導向活動通報名頁面
