### ISSUE TITLE
CSS導致黑線

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#560]
![image](https://cloud.githubusercontent.com/assets/698579/18666499/b31a8a50-7f5e-11e6-81e0-c751c07a26ac.png)

![image](https://cloud.githubusercontent.com/assets/698579/18666490/aae7fe30-7f5e-11e6-93a6-18dd7bd53916.png)

**Comment by sakuxz** [comment]
#474 
目前已 pr
