### ISSUE TITLE
訂單的後台還需要考慮狀態的變更，還有狀態的篩選

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#563]
訂單的後台還需要考慮狀態的變更，還有狀態的篩選

* 製作中 PROCESSING
* 製作完成  COMPLETED_PROCESSING

其中狀態塞選可用下拉選單

**Comment by smlsunxie** [comment]
補充：此功能的目的是要讓訂單處理更方便，將會搭配 CSV 使用，訂單狀態方便現場人員將不同階段需要處理的資料進行分類

**Comment by smlsunxie** [comment]
客制 datatable  的 ajax paging request 可以參考 

https://datatables.net/examples/ajax/custom_data_property.html

ex: 

```
$(document).ready(function() {
    $('#example').DataTable( {
        "ajax": {
            "url": "data/arrays_custom_prop.txt?status= PROCESSING",
            "dataSrc": "demo"
        }
    } );
} );

```

**Comment by lyhcode** [comment]
`COMPLETED_PROCESSING` 應該用 `COMPLETED` 就可以了，後面的 PROCESSING 很多餘。

**Comment by smlsunxie** [comment]
`COMPLETED` 已有定義，比較像整個訂單處理完成

**Comment by smlsunxie** [comment]
更正 客制塞選範例

https://datatables.net/examples/server_side/custom_vars.html

**Comment by smlsunxie** [comment]
關於狀態 `DONE` 也是一個選擇

**Comment by smlsunxie** [comment]
在更正 https://github.com/trunk-studio/cargocms/issues/563#issuecomment-248347824
使用於第一次 request

這才是使用於 filter

$('#myTable').DataTable( {
    serverSide: true,
    ajax: {
        url: '/api/data',
        dataFilter: function(data){
            var json = jQuery.parseJSON( data );
            json.recordsTotal = json.total;
            json.recordsFiltered = json.total;
            json.data = json.list;
 
            return JSON.stringify( json ); // return JSON string
        }
    }
} );
