### ISSUE TITLE
"我要回去"感覺怪怪的

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#581]
![image](https://cloud.githubusercontent.com/assets/698579/18704501/b67b9aea-801c-11e6-9b8b-4ef507da7309.png)

**Comment by dd-han** [comment]
關閉畫面、關閉、不登出、離開、離開畫面

我想到的詞

**Comment by lyhcode** [comment]
"算了吧"
"我不要"
"取消"
"取消動作"
"繼續使用"
"繼續停留"
"繼續逗留"

**Comment by lyhcode** [comment]
這個也開放給大家自己挑合適的，除非客戶有指定要用什麼

**Comment by smlsunxie** [comment]
取消
