### ISSUE TITLE
訂單後台再調整

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#617]
![image](https://cloud.githubusercontent.com/assets/1689227/18761682/88f93c4a-8138-11e6-9864-26c6da8eeed3.png)

**Comment by smlsunxie** [comment]
訂單尚未成立是什麼情形，需要釐清

**Comment by smlsunxie** [comment]
付款時間之外，應該要有訂單建立時間，預設應該要最近的訂單排在最上面

**Comment by FuYaoDe** [comment]
訂單尚未成立 是因為 allpay 用 atm 付款的話有兩個步驟 第一個步驟選擇轉帳銀行，這時候訂單還沒成立，到第二步驟才會出現轉帳帳號這時候訂單才建立完成
