### ISSUE TITLE
登入、登出後在重新進入登入畫面，會出現「帳號密碼錯誤」的訊息

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#668]
我都還沒輸入錯誤的帳號密碼，就出現錯誤。

但是機率出現，還不確定要怎麼讓它100%重現

**Comment by smlsunxie** [comment]
應該是曾經登入過在登出，再去點選該按鈕會有這樣的問題

**Comment by dd-han** [comment]
確定100%重現方式：

用Facebook登入系統，登出系統回到首頁後，再按下「登入」或是「登入配方創作系統」，就會出現「帳號或密碼錯誤！」的訊息
