### ISSUE TITLE
手機看導覽列有多餘的項目

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#672]
![screenshot_20160923-233521](https://cloud.githubusercontent.com/assets/5909203/18791711/767cf6ec-8179-11e6-9932-48061d664e8e.png)

**Comment by sakuxz** [comment]
你是說哪一個地方
導覽列的2px在手機板是 display: none
應該不是他的問題

**Comment by dd-han** [comment]
@sakuxz 「陳奕翰」下面多一條線

本來「陳奕翰」下面應該只有一條線，但是現在變成一條線、底色、一條線

**Comment by dd-han** [comment]
上色那裡是還有一個一個空項目被看到

當然這非常不明顯，絕對不是有優先度的問題
![767cf6ec-8179-11e6-9932-48061d664e8e](https://cloud.githubusercontent.com/assets/5909203/18824870/d9ff5004-83f7-11e6-93c4-998a3dff13d1.png)

**Comment by sakuxz** [comment]
OK  應該要解決  但那不是為了解決2px的code造成的

**Comment by dd-han** [comment]
查出來了，那條線是原本選單未展開就在那裡的分隔線，是否要考慮展開後隱藏那條線？

![2016-10-04 18-08-19](https://cloud.githubusercontent.com/assets/5909203/19070386/95c2ca12-8a5d-11e6-9699-e7ebe6cd39c0.png)
![2016-10-04 18-08-22](https://cloud.githubusercontent.com/assets/5909203/19070390/9b93dbca-8a5d-11e6-9e59-45bb761fa6e8.png)
