### ISSUE TITLE
首頁Logo似乎有縮放過？鋸齒非常嚴重

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#695]

**Comment by dd-han** [comment]
不上白底黑色明顯有鋸齒

![2016-09-24_01-06-22](https://cloud.githubusercontent.com/assets/5909203/18794743/9dc064e4-81f3-11e6-96a2-8ff80bb9ae5c.png)
![2016-09-24_01-06-45](https://cloud.githubusercontent.com/assets/5909203/18794745/9de82394-81f3-11e6-8455-e957b8d0a3ea.png)

**Comment by dd-han** [comment]
上了黑底，文字明顯歪曲變形
![2016-09-24_01-09-02](https://cloud.githubusercontent.com/assets/5909203/18794760/a9cb6d1a-81f3-11e6-9760-200fff1aa65c.png)

**Comment by dd-han** [comment]
黑色的部份有做反鋸齒處理，但是白色的部份沒做反鋸齒

可能需要跟他們討論或是索取原圖？

**Comment by lyhcode** [comment]
我一開始有發現，但他們給的原圖就有明顯鋸齒，除非從向量圖重新出圖

**Comment by dd-han** [comment]
在想有沒有可能用svg向量圖？因為現在除了鋸齒問題，還有檔案太大導致手機載入等……超久的問題

要縮小檔案得用jpg，可是jpg不支援透明底圖。還是說用gif？反正只有灰階，gif的256色限制好像沒關係
