### ISSUE TITLE
時間格式統一處理

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#741]
為了因應不同時區的處理，元 model 的 `createdAt` 跟 `updatedAt` 不允許進行 datetime format

統一用虛擬欄位進行轉換，目前會有兩個狀況
1. iso format
2. readable format

需要將所有 model 加上相關欄位，以便讓前端或是串接 api 可以方便使用

**Comment by tikka0910** [comment]
請問model 時間的用虛擬欄位所輸出的時間格式 ，[ 2016-12-25 14:30:00 ] 是採用這樣的格式嗎？

**Comment by tikka0910** [comment]
model  虛擬欄位 readable 時間預計輸出 一個 object `{datatime: '2016-12-25 14:30:00', data: '2016-12-25', time:'14:30:00'}` 這樣的時間格式，這樣可以在前端直接取得想要的部分顯示。

**Comment by tikka0910** [comment]
請問 虛擬欄位的名稱建議使用什麼樣子的名稱呢？

**Comment by tikka0910** [comment]
欄位名稱 createdDateTime, updatedDateTime

獨立處理時間格式的 function 檔案，在 model 內匯入檔案

createdDateTime & updateDateTime 統一使用 function 輸出時間
