### ISSUE TITLE
後台訂單資料與歐付寶交易記錄無法對應

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#771]

**Comment by smlsunxie** [comment]
交易編號，若不是使用金流應該為空白，該欄位為訂單與 allpay 的後台訂單的對應編號
交易編號與廠商交易編號，都顯示在後台清單的第一層

如此就可以區分哪些可以跟 allpay 進行對應

**Comment by smlsunxie** [comment]
廠商交易編號  > 更名為 訂單編號
交易編號 > 更名為 金流交易編號
