### ISSUE TITLE
Contact 表單行為

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/cargocms#847]
使用者送出後，寄一封信給站台設定的客服信箱

e.g.

```
info@labfnp.com
```

from 的設定用網站預設的發信帳號

replyTo 的設定則是表單的填寫者Email

![image](https://cloud.githubusercontent.com/assets/698579/19225867/0e4fc7ce-8ed6-11e6-9047-23b13b2b1bd7.png)

**Comment by FuYaoDe** [comment]
contact 頁面新增一個  `發送訊息給粉絲頁` 
https://www.facebook.com/messages/LabFnP
