### ISSUE TITLE
檔案過大無提示(find-uploader)

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#875]
4MB以上會跳警告，但是介於1.1MB~3MB都不會跳警告

![image](https://cloud.githubusercontent.com/assets/5909203/19298819/19768da0-9083-11e6-847c-84a4f25b952e.png)

**Comment by FuYaoDe** [comment]
修改位置
https://github.com/trunk-studio/cargocms/blame/master/assets-labfnp/lib/fineuploader.js#L26

**Comment by dd-han** [comment]
https://home.dd-han.tw/index/sample/2015-08-18%2019_57_26-.png
這個4.1MB的png會直接被擋下來，沒啥問題

https://home.dd-han.tw/index/sample/2015-08-18%2019_55_25-.png
這個3MB的png不會被擋下來，可是會傳輸失敗

**Comment by FuYaoDe** [comment]
3 MB 是因為 `413 (Request Entity Too Large)` 
解決辦法有這三種
```
更改 nginx 設置 
在前端壓縮圖片
限制上傳大小 
```

**Comment by dd-han** [comment]
nginx的設定：

`client_max_body_size 16400M;`

**Comment by FuYaoDe** [comment]
目前 fineupload 已經有提示，但是 413 (Request Entity Too Large) 問題，所以預計會做前端壓縮圖片
