### ISSUE TITLE
香水筆記

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#922]
![image](https://cloud.githubusercontent.com/assets/1689227/19423568/3e76672c-9454-11e6-8974-08a299f6cdd4.png)

我的收藏旁邊，多一個 `我的筆記`

列出有作 feedback 的 recipe

![image](https://cloud.githubusercontent.com/assets/1689227/19423594/6edf0d24-9454-11e6-9177-45c42e3ab59b.png)

檢視的時候在下面顯示針對 香味還有配方的 feedback

**Comment by FuYaoDe** [comment]
那個地方的按鈕已經太多了 在手機版不好顯示
我是覺得擺在

![screenshot 2016-10-17 10 33 06](https://cloud.githubusercontent.com/assets/6357215/19423657/1ddd42c8-9455-11e6-8689-a82ad48c6f51.png)

左下方有個香味筆記比較好

**Comment by smlsunxie** [comment]
這個位置我有想過，也是選項之一

**Comment by FuYaoDe** [comment]
上次錄音檔 52:50 開始討論這個功能

**Comment by kuyen** [comment]
我也覺得在個人頁面裡面比較好
