### ISSUE TITLE
第三方支付防偽機制

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#974]
使用 訂單編號 + recipe name + secret code 來作為編碼

使用套件 https://github.com/bibig/node-shorthash

以下面的交易資料為例

![image](https://cloud.githubusercontent.com/assets/1689227/19632602/c60371d6-99da-11e6-8e8b-7554234d79d4.png)

訂單編號    e47f8519

商品明細    Meet 100 ml

若使用 shorthash 進行編碼字串為 `e47f8519-Meet-22019020`

其中 `22019020` 可以是一個 secret code

編碼出來的字串為 `LgPJv`

只要是相同的字母則編碼結果將會相同，如此就可以用於確認該 code 是否可以用相同規則做產出

至於在商品明細上就可以改為下面方式呈現

商品明細    `Meet 100 ml check:LgPJv`

考量到商品明細有欄位大小的限制，盡可能縮短

**Comment by smlsunxie** [comment]
samle code 

```
console.log(sh.unique('e47f8519-Meet-22019020'));
```

**Comment by lyhcode** [comment]
`配方名稱 100ml [PJv]`    取後三碼當CRC檢核碼 + 括號識別即可

**Comment by smlsunxie** [comment]
OK
